muikku/src/main/java/fi/otavanopisto/muikku/i18n/LocaleBackingBean.java
package fi.otavanopisto.muikku.i18n;

import java.util.Collections;
import java.util.List;
import java.util.Map;

import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import fi.otavanopisto.muikku.i18n.LocaleController;
import fi.otavanopisto.muikku.session.SessionController;

@Named("i18n")
@Stateful
@RequestScoped
public class LocaleBackingBean {

  @Inject
  private SessionController sessionController;
  
  @Inject
  private LocaleController localeController;

  public Map<String, String> getText() {
    return localeController.getText(sessionController.getLocale());
  }
  
  public List<String> getLanguages() {
    List<String> result = localeController.getLanguages();
    String currentLanguage = sessionController.getLocale().getLanguage();
    Collections.sort(result);
    result.remove(currentLanguage);
    result.add(0, currentLanguage);
    return result;
  }

}

muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
package fi.otavanopisto.muikku.session;

import java.time.OffsetDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import fi.otavanopisto.muikku.controller.SystemSettingsController;
import fi.otavanopisto.muikku.i18n.LocaleController;
import fi.otavanopisto.muikku.model.users.EnvironmentRoleArchetype;
import fi.otavanopisto.muikku.model.users.EnvironmentRoleEntity;
import fi.otavanopisto.muikku.model.users.UserEntity;
import fi.otavanopisto.muikku.model.workspace.WorkspaceEntity;
import fi.otavanopisto.muikku.plugins.forum.ForumController;
import fi.otavanopisto.muikku.plugins.forum.ForumResourcePermissionCollection;
import fi.otavanopisto.muikku.plugins.forum.model.EnvironmentForumArea;
import fi.otavanopisto.muikku.plugins.workspace.WorkspaceBackingBean;
import fi.otavanopisto.muikku.schooldata.SchoolDataIdentifier;
import fi.otavanopisto.muikku.schooldata.UserSchoolDataController;
import fi.otavanopisto.muikku.schooldata.WorkspaceEntityController;
import fi.otavanopisto.muikku.schooldata.entity.User;
import fi.otavanopisto.muikku.schooldata.entity.UserAddress;
import fi.otavanopisto.muikku.schooldata.entity.UserPhoneNumber;
import fi.otavanopisto.muikku.schooldata.entity.UserProperty;
import fi.otavanopisto.muikku.users.UserController;
import fi.otavanopisto.muikku.users.UserEmailEntityController;
import fi.otavanopisto.muikku.users.UserSchoolDataIdentifierController;

@RequestScoped
@Named
@Stateful
public class SessionBackingBean {

  @Inject
  private SessionController sessionController;

  @Inject
  private LocaleController localeController;

  @Inject
  private UserController userController;

  @Inject
  private WorkspaceEntityController workspaceEntityController;

  @Inject
  private SystemSettingsController systemSettingsController;

  @Inject
  private WorkspaceBackingBean workspaceBackingBean;

  @Inject
  private ForumController forumController;

  @Inject
  private UserEmailEntityController userEmailEntityController;

  @Inject
  private UserSchoolDataController userSchoolDataController;
  
  @Inject
  private UserSchoolDataIdentifierController userSchoolDataIdentifierController;

  @PostConstruct
  public void init() {
    loggedUserRoleArchetype = null;
    loggedUserName = null;
    testsRunning = StringUtils.equals("true", System.getProperty("tests.running"));
    bugsnagApiKey = systemSettingsController.getSetting("bugsnagApiKey");
    bugsnagEnabled = StringUtils.isNotBlank(bugsnagApiKey);
    loggedUserId = null;
    loggedUser = null;
    canAccessEnvironmentForum = forumController.isEnvironmentForumActive() && hasEnvironmentPermission(ForumResourcePermissionCollection.FORUM_ACCESSENVIRONMENTFORUM);

    if (sessionController.isLoggedIn()) {
      UserEntity loggedUser = sessionController.getLoggedUserEntity();
      if (loggedUser != null) {
        String activeSchoolDataSource = sessionController.getLoggedUserSchoolDataSource();
        String activeUserIdentifier = sessionController.getLoggedUserIdentifier();
        
        EnvironmentRoleEntity roleEntity = userSchoolDataIdentifierController.findUserSchoolDataIdentifierRole(sessionController.getLoggedUser());
        if (roleEntity != null) {
          loggedUserRoleArchetype = roleEntity.getArchetype();
        }

        User user = userController.findUserByDataSourceAndIdentifier(activeSchoolDataSource, activeUserIdentifier);
        if (user != null) {
          if (!loggedUserRoleArchetype.equals(EnvironmentRoleArchetype.STUDENT)) {
            loggedUserName = String.format("%s %s (%s)", user.getFirstName(), user.getLastName(),
                resolveLoggedUserRoleText());
          }
          else if (user.getNickName() != null) {
            loggedUserName = String.format("%s %s (%s)", user.getNickName(), user.getLastName(),
                user.getStudyProgrammeName());
          }
          else {
            loggedUserName = user.getDisplayName();
          }
        }
      }

      this.loggedUserId = sessionController.getLoggedUserEntity().getId();
      this.loggedUser = sessionController.getLoggedUser().toId();

      if (!sessionController.hasEnvironmentPermission(ForumResourcePermissionCollection.FORUM_ACCESSENVIRONMENTFORUM)
          || !sessionController.isActiveUser()) {
        this.areaPermissions = null;
      }
      else {
        List<EnvironmentForumArea> forumAreas = forumController.listEnvironmentForums();
        Map<Long, AreaPermission> areaPermissions = new HashMap<>();

        for (EnvironmentForumArea forumArea : forumAreas) {
          AreaPermission areaPermission = new AreaPermission(
              sessionController.hasPermission(ForumResourcePermissionCollection.FORUM_EDIT_ENVIRONMENT_MESSAGES,
                  forumArea),
              sessionController.hasPermission(ForumResourcePermissionCollection.FORUM_DELETE_ENVIRONMENT_MESSAGES,
                  forumArea));
          areaPermissions.put(forumArea.getId(), areaPermission);
        }

        try {
          this.areaPermissions = new ObjectMapper().writeValueAsString(areaPermissions);
        }
        catch (JsonProcessingException e) {
          this.areaPermissions = null;
        }
      }
    }
    else {
      this.areaPermissions = null;
    }

    if (sessionController.isLoggedIn()) {
      UserEntity userEntity = sessionController.getLoggedUserEntity();
      User user = userController.findUserByDataSourceAndIdentifier(sessionController.getLoggedUserSchoolDataSource(), sessionController.getLoggedUserIdentifier());
      List<UserAddress> userAddresses = userController.listUserAddresses(user);
      List<UserPhoneNumber> userPhoneNumbers = userController.listUserPhoneNumbers(user);
        
      displayName = user.getNickName() == null ? user.getDisplayName() : String.format("%s %s (%s)", user.getNickName(), user.getLastName(), user.getStudyProgrammeName());
        
      studyStartDate = user.getStudyStartDate();
      studyEndDate = user.getStudyEndDate();
      studyTimeEnd = user.getStudyTimeEnd();
      studyTimeLeftStr = "";

      if (studyTimeEnd != null) {
        OffsetDateTime now = OffsetDateTime.now();
        Locale locale = sessionController.getLocale();
          
        if (now.isBefore(studyTimeEnd)) {
          long studyTimeLeftYears = now.until(studyTimeEnd, ChronoUnit.YEARS);
          now = now.plusYears(studyTimeLeftYears);
          if (studyTimeLeftYears > 0) {
            studyTimeLeftStr += studyTimeLeftYears + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.y");
          }
            
          long studyTimeLeftMonths = now.until(studyTimeEnd, ChronoUnit.MONTHS);
          now = now.plusMonths(studyTimeLeftMonths);
          if (studyTimeLeftMonths > 0) {
            if (studyTimeLeftStr.length() > 0)
              studyTimeLeftStr += " ";
            studyTimeLeftStr += studyTimeLeftMonths + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.m");
          }
          
          long studyTimeLeftDays = now.until(studyTimeEnd, ChronoUnit.DAYS);
          now = now.plusDays(studyTimeLeftDays);
          if (studyTimeLeftDays > 0) {
            if (studyTimeLeftStr.length() > 0)
              studyTimeLeftStr += " ";
            studyTimeLeftStr += studyTimeLeftDays + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.d");
          }
        }

        long studyTimeLeftMonths = now.until(studyTimeEnd, ChronoUnit.MONTHS);
        now = now.plusMonths(studyTimeLeftMonths);
        if (studyTimeLeftMonths > 0) {
          if (studyTimeLeftStr.length() > 0)
            studyTimeLeftStr += " ";
          studyTimeLeftStr += studyTimeLeftMonths + " "
              + localeController.getText(locale, "plugin.profile.studyTimeEndShort.m");
        }

        long studyTimeLeftDays = now.until(studyTimeEnd, ChronoUnit.DAYS);
        now = now.plusDays(studyTimeLeftDays);
        if (studyTimeLeftDays > 0) {
          if (studyTimeLeftStr.length() > 0)
            studyTimeLeftStr += " ";
          studyTimeLeftStr += studyTimeLeftDays + " "
            + localeController.getText(locale, "plugin.profile.studyTimeEndShort.d");
        }
      }

      ArrayList<String> foundAddresses = new ArrayList<>();
      for (UserAddress userAddress : userAddresses) {
        foundAddresses.add(String.format("%s %s %s %s", userAddress.getStreet(), userAddress.getPostalCode(),
            userAddress.getCity(), userAddress.getCountry()));
      }
      try {
        this.addresses = new ObjectMapper().writeValueAsString(foundAddresses);
      } catch (JsonProcessingException e) {
        this.addresses = null;
      }

      ArrayList<String> foundPhoneNumbers = new ArrayList<>();
      for (UserPhoneNumber userPhoneNumber : userPhoneNumbers) {
        foundPhoneNumbers.add(userPhoneNumber.getNumber());
      }

      try {
        this.phoneNumbers = new ObjectMapper().writeValueAsString(foundPhoneNumbers);
      } catch (JsonProcessingException e) {
        this.phoneNumbers = null;
      }

      SchoolDataIdentifier identifier = userEntity.defaultSchoolDataIdentifier();
      List<String> foundEmails = userEmailEntityController.getUserEmailAddresses(identifier);
      try {
        this.emails = new ObjectMapper().writeValueAsString(foundEmails);
      } catch (JsonProcessingException e) {
        this.emails = null;
      }
    }
  }

  public boolean getLoggedIn() {
    return sessionController.isLoggedIn();
  }

  public boolean getIsStudent() {

muikku/src/main/webapp/WEB-INF/templates/base.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:jsf="http://xmlns.jcp.org/jsf"
  xmlns:ui="http://java.sun.com/jsf/facelets">

<!-- Base takes no parameters -->
<!-- Base takes four defines, styles, scripts, body and title, where title is not required -->

<f:view locale="#{sessionBackingBean.locale}">

<head>
  <title>#{empty title ? i18n.text['plugin.site.title'] : title}</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta content="width=device-width, initial-scale=1.0, minimum-scale=1, maximum-scale=1" name="viewport" />
  <script type="text/javascript">
    var CONTEXTPATH = "#{request.contextPath}";
    var MUIKKU_LOGGED_USER_ID = parseInt('#{sessionBackingBean.loggedUserId}')||null;
    var MUIKKU_LOGGED_USER = '#{sessionBackingBean.loggedUser}'||null;
    var MUIKKU_LOGGEDIN = #{sessionBackingBean.loggedIn};
    var MUIKKU_IS_ACTIVE_USER = #{sessionBackingBean.isActiveUser};
    var MUIKKU_IS_STUDENT = #{sessionBackingBean.isStudent};
    var PROFILE_DATA = {
      displayName: '#{sessionBackingBean.displayName}' || null,
      emails: #{sessionBackingBean.emails},
      addresses: #{sessionBackingBean.addresses},
      phoneNumbers: #{sessionBackingBean.phoneNumbers},
      studyTimeLeftStr: '#{sessionBackingBean.studyTimeLeftStr}'  || null,
      studyStartDate: '#{sessionBackingBean.studyStartDate}'  || null,
      studyEndDate: '#{sessionBackingBean.studyEndDate}' || null,
      studyTimeEnd: '#{sessionBackingBean.studyTimeEnd}' || null
    }
    var HOPS_ENABLED = #{sessionBackingBean.getUserPropertyAsBoolean('hops.enabled')};

    var MUIKKU_PERMISSIONS = {
      FORUM_ACCESSENVIRONMENTFORUM: #{sessionBackingBean.canAccessEnvironmentForum},
      GUIDER_VIEW: #{sessionBackingBean.hasEnvironmentPermission('GUIDER_VIEW')},
      TRANSCRIPT_OF_RECORDS_VIEW: #{sessionBackingBean.hasEnvironmentPermission('TRANSCRIPT_OF_RECORDS_VIEW')},
      EVALUATION_VIEW_INDEX: #{sessionBackingBean.hasEnvironmentPermission('EVALUATION_VIEW_INDEX')},
      ANNOUNCER_TOOL: #{sessionBackingBean.hasEnvironmentPermission('ANNOUNCER_TOOL')},
      ANNOUNCER_CAN_PUBLISH_ENVIRONMENT: #{sessionBackingBean.hasEnvironmentPermission('CREATE_ANNOUNCEMENT')},
      ANNOUNCER_CAN_PUBLISH_WORKSPACES: true,
      ANNOUNCER_CAN_PUBLISH_GROUPS: #{sessionBackingBean.hasEnvironmentPermission('CREATE_ANNOUNCEMENT')},

      COMMUNICATOR_GROUP_MESSAGING: #{sessionBackingBean.hasEnvironmentPermission('COMMUNICATOR_GROUP_MESSAGING')},
      COMMUNICATOR_WORKSPACE_MESSAGING: #{sessionBackingBean.hasEnvironmentPermission('COMMUNICATOR_WORKSPACE_MESSAGING')},

      AREA_PERMISSIONS: #{sessionBackingBean.areaPermissions},
      FORUM_LOCK_STICKY_PERMISSION: #{sessionBackingBean.hasEnvironmentPermission('FORUM_LOCK_OR_STICKIFY_MESSAGES')},
      FORUM_SHOW_FULL_NAME_PERMISSION: #{sessionBackingBean.hasEnvironmentPermission('FORUM_SHOW_FULL_NAMES')},
      FORUM_CREATEENVIRONMENTFORUM: #{sessionBackingBean.hasEnvironmentPermission('FORUM_CREATEENVIRONMENTFORUM')},
      FORUM_UPDATEENVIRONMENTFORUM: #{sessionBackingBean.hasEnvironmentPermission('FORUM_UPDATEENVIRONMENTFORUM')},
      FORUM_DELETEENVIRONMENTFORUM: #{sessionBackingBean.hasEnvironmentPermission('FORUM_DELETEENVIRONMENTFORUM')}
    }
  </script>

  <ui:fragment rendered="#{sessionBackingBean.bugsnagEnabled}">
    <script defer="defer" type="text/javascript"
      src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js"
      data-apikey="#{sessionBackingBean.bugsnagApiKey}"></script>
  </ui:fragment>

  <!-- jQuery -->
  <script type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery/2.1.3/jquery.min.js" />

  <!-- jQuery UI -->
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jqueryui/1.11.2/jquery-ui.min.js" />
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jqueryui/1.11.2/i18n/datepicker-fi.js" />

  <script defer="defer" type="text/javascript">
    $(document).ready(function () {
      $.datepicker.setDefaults($.datepicker.regional['#{sessionBackingBean.locale}']);
    });
  </script>

  <ui:fragment rendered="#{sessionBackingBean.testsRunning}">
    <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate/1.0.1/jquery.simulate.js"></script>
    <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate-ext/1.3.0/jquery.simulate.ext.js"></script>
    <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate-ext/1.3.0/jquery.simulate.drag-n-drop.js"></script>
  </ui:fragment>

  <script defer="defer" type="text/javascript" jsf:name="/scripts/debug.js" jsf:rendered="#{sessionBackingBean.testsRunning}" />

  <!-- Moment -->
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/moment/2.10.6/moment-with-locales.min.js" />

  <!-- Interactions -->
  <script defer="defer" type="text/javascript" jsf:name="/scripts/extensions.js" />

  <!-- Api resources -->
  <script defer="defer" type="text/javascript" src="#{request.contextPath}/rest/meta/resources?format=js"></script>

  <!-- Async -->
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/async/0.9.0/async.js" />

  <!-- ObjectPath, jQuery REST -->
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/interpreter.js"></script>
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/parse.js"></script>
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/tokens.js"></script>
  <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery.rest/1.0.2/jquery.rest.min.js"></script>

  <!-- Api -->
  <script defer="defer" type="text/javascript" jsf:name="/scripts/api/api.js" />

  <!-- Heartbeat -->
  <script defer="defer" type="text/javascript" jsf:name="/scripts/gui/heartbeat.js" />

  <!-- Language -->
  <script defer="defer" type="text/javascript" jsf:name="/scripts/gui/language.js" />

  <!-- JavaScript locales -->
  <script defer="defer" type="text/javascript" src="#{request.contextPath}/JavaScriptLocales?lang=#{sessionBackingBean.locale}" />

  <!-- locales -->
  <script defer="defer" jsf:name="scripts/gui/locales.js" />

  <!-- Flex Grid, DEPRECATED -->
  <link rel="stylesheet" type="text/css" href="//cdn.muikkuverkko.fi/libs/fni-flexgrid/1.0.0/flexgrid.css" />

  <!-- Converse if required -->
  <ui:fragment rendered="#{sessionBackingBean.loggedIn}">
<!--     <script defer="defer" jsf:name="scripts/gui/chat.js" /> -->
<!--     <script defer="defer" src="//cdn.muikkuverkko.fi/libs/converse-muikku/1.1.5/converse-no-jquery.min.js"/> -->
<!--     <link rel="stylesheet" type="text/css" href="//cdn.muikkuverkko.fi/libs/converse-muikku/1.1.5/converse.min.css" /> -->
  </ui:fragment>

  <!-- Muikku icons -->
  <link rel="stylesheet" type="text/css" href="//cdn.muikkuverkko.fi/assets/muikku-icons/1.2.5/style.css" />
  <ui:insert name="styles"></ui:insert>

  <!-- Here goes what a page needs, usually their controllers -->
  <ui:insert name="scripts"></ui:insert>
</head>

<body>
  <div id="app"></div>

  <!-- TODO: please lets find a way to do this with a rest endpoint -->
  <h:form id="language-picker" style="display:none">
    <ui:repeat value="#{i18n.languages}" var="locale">
      <a jsf:action="#{languageWidgetBackingBean.setLanguage(locale)}" data-locale="#{locale}">
        #{i18n.text['plugin.navigation.language.' .concat(locale)]}
      </a>
    </ui:repeat>
  </h:form>
  <h:form style="display:none">
    <a jsf:action="#{logoutWidgetBackingBean.logout}" id="logout"></a>
  </h:form>
  <a id="locale" style="display:none">#{languageWidgetBackingBean.language}</a>
  <a id="login" style="display:none" jsf:outcome="/login.jsf?authSource=loginWidgetBackingBean.credentialessAuthSources[0]"></a>

  <!-- Google Analytics -->
  <script>
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
    ga('create', 'UA-7407719-33', 'auto');
    ga('send', 'pageview');
  </script>
  <script async="async" src='https://www.google-analytics.com/analytics.js'></script>
  <!-- End Google Analytics -->
</body>

</f:view>
</html>

muikku/src/main/webapp/WEB-INF/templates/error.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:jsf="http://xmlns.jcp.org/jsf"
  template="base.xhtml">
  
  <ui:define name="scripts">
    <script defer="defer">
	  MUIKKU_ERROR_TITLE = "#{errorTitle}";
	  MUIKKU_ERROR_DESCRIPTION = "#{errorDescription}";
    </script>
    <script defer="defer" jsf:name="scripts/dist/vendor.js" />
    <script defer="defer" jsf:name="scripts/dist/error.js" />
  </ui:define>
  
  <ui:define name="styles">
    <link rel="stylesheet" type="text/css" href="/scripts/dist/error.css" />
  </ui:define>

</ui:composition>