muikku/src/main/java/fi/otavanopisto/muikku/EnvironmentBackingBean.java
package fi.otavanopisto.muikku;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;

import fi.otavanopisto.muikku.controller.SystemSettingsController;

@ApplicationScoped
@Named
@Stateful
public class EnvironmentBackingBean {
  
  private static final String ANALYTICS_GOOGLEANALYTICS_KEY_SETTING = "analytics.googleAnalytics.trackingID";
  
  @Inject
  private SystemSettingsController systemSettingsController;

  @PostConstruct
  public void init() {
    helpWorkspaceUrlName = systemSettingsController.getHelpWorkspaceUrlName();
    hasWorkspaceUrlName = StringUtils.isNotBlank(helpWorkspaceUrlName);
    
    googleAnalyticsTrackingId = systemSettingsController.getSetting(ANALYTICS_GOOGLEANALYTICS_KEY_SETTING);
  }
  
  public String getHelpWorkspaceUrlName() {
    return helpWorkspaceUrlName;
  }
  
  public boolean getHasWorkspaceUrlName() {
    return hasWorkspaceUrlName;
  }
  
  public String getGoogleAnalyticsTrackingId() {
    return googleAnalyticsTrackingId;
  }
  
  public boolean getHasGoogleAnalyticsTrackingId() {
    return StringUtils.isNotBlank(googleAnalyticsTrackingId);
  }

  private String helpWorkspaceUrlName;
  private boolean hasWorkspaceUrlName;
  private String googleAnalyticsTrackingId;
}

muikku/src/main/java/fi/otavanopisto/muikku/JavaScriptLocaleServlet.java
package fi.otavanopisto.muikku;

import java.io.IOException;
import java.io.PrintWriter;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.LocaleUtils;

import fi.otavanopisto.muikku.i18n.LocaleController;

@WebServlet(name = "JavaScriptLocaleServlet", urlPatterns = "/JavaScriptLocales")
public class JavaScriptLocaleServlet extends HttpServlet {

  private static final long serialVersionUID = 1L;

  @Inject
  private LocaleController localeController;

  @Override
  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    response.setContentType("application/javascript");
    PrintWriter writer = response.getWriter();
    writer.write(localeController.getJsLocales(LocaleUtils.toLocale(request.getParameter("lang"))));
    writer.flush();
    writer.close();
  }

  @Override
  protected long getLastModified(HttpServletRequest req) {
    Long lastModified = localeController.getJsLastModified((LocaleUtils.toLocale(req.getParameter("lang"))));
    if (lastModified != null) {
    	return lastModified;
    }
    
    return super.getLastModified(req);
  }

}

muikku/src/main/java/fi/otavanopisto/muikku/files/TempFileUploadServlet.java
package fi.otavanopisto.muikku.files;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;

import org.apache.commons.io.IOUtils;
import org.codehaus.jackson.map.ObjectMapper;

import fi.otavanopisto.muikku.controller.SystemSettingsController;
import fi.otavanopisto.muikku.files.TempFileUtils;

@MultipartConfig
@WebServlet("/tempFileUploadServlet")
public class TempFileUploadServlet extends HttpServlet {

  private static final long serialVersionUID = -4689635910226270913L;

  @Inject
  private SystemSettingsController systemSettingsController;

  @Override
  protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    Part file = req.getPart("file");

    long fileSizeLimit = systemSettingsController.getUploadFileSizeLimit();

    if (file.getSize() > fileSizeLimit) {
      resp.setStatus(HttpServletResponse.SC_REQUEST_ENTITY_TOO_LARGE);
      return;
    }

    File tempFile = TempFileUtils.createTempFile();
    FileOutputStream fileOutputStream = new FileOutputStream(tempFile);
    InputStream input = file.getInputStream();
    try {
      IOUtils.copy(input, fileOutputStream);
    } finally {
      fileOutputStream.flush();
      fileOutputStream.close();
      IOUtils.closeQuietly(input);
    }

    Map<String, String> output = new HashMap<>();
    output.put("fileId", tempFile.getName());
    String fileName = getFileName(file);
    if (fileName != null) {
      output.put("fileContentType", getServletContext().getMimeType(fileName));
    }

    resp.setContentType("application/json");
    ServletOutputStream servletOutputStream = resp.getOutputStream();
    try {
      (new ObjectMapper()).writeValue(servletOutputStream, output);
    } finally {
      servletOutputStream.flush();
    }
  }

  private String getFileName(final Part part) {
    for (String content : part.getHeader("content-disposition").split(";")) {
      if (content.trim().startsWith("filename")) {
        return content.substring(content.indexOf('=') + 1).trim().replace("\"", "");
      }
    }
    return null;
  }

}

muikku/src/main/java/fi/otavanopisto/muikku/i18n/LocaleBackingBean.java
package fi.otavanopisto.muikku.i18n;

import java.util.Collections;
import java.util.List;
import java.util.Map;

import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import fi.otavanopisto.muikku.i18n.LocaleController;
import fi.otavanopisto.muikku.session.SessionController;

@Named("i18n")
@Stateful
@RequestScoped
public class LocaleBackingBean {

  @Inject
  private SessionController sessionController;
  
  @Inject
  private LocaleController localeController;

  public Map<String, String> getText() {
    return localeController.getText(sessionController.getLocale());
  }
  
  public List<String> getLanguages() {
    List<String> result = localeController.getLanguages();
    String currentLanguage = sessionController.getLocale().getLanguage();
    Collections.sort(result);
    result.remove(currentLanguage);
    result.add(0, currentLanguage);
    return result;
  }

}

muikku/src/main/java/fi/otavanopisto/muikku/servlet/HeartbeatServlet.java
package fi.otavanopisto.muikku.servlet;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/heartbeat")
public class HeartbeatServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	  
	  request.getSession(false); // keep session alive
	  
	  response.setStatus(HttpServletResponse.SC_NO_CONTENT);
	}

}

muikku/src/main/java/fi/otavanopisto/muikku/session/SessionBackingBean.java
package fi.otavanopisto.muikku.session;

import java.time.OffsetDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.ejb.Stateful;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import fi.otavanopisto.muikku.controller.SystemSettingsController;
import fi.otavanopisto.muikku.i18n.LocaleController;
import fi.otavanopisto.muikku.model.users.EnvironmentRoleArchetype;
import fi.otavanopisto.muikku.model.users.EnvironmentRoleEntity;
import fi.otavanopisto.muikku.model.users.UserEntity;
import fi.otavanopisto.muikku.model.workspace.WorkspaceEntity;
import fi.otavanopisto.muikku.plugins.forum.ForumController;
import fi.otavanopisto.muikku.plugins.forum.ForumResourcePermissionCollection;
import fi.otavanopisto.muikku.plugins.forum.model.EnvironmentForumArea;
import fi.otavanopisto.muikku.plugins.workspace.WorkspaceBackingBean;
import fi.otavanopisto.muikku.schooldata.SchoolDataIdentifier;
import fi.otavanopisto.muikku.schooldata.UserSchoolDataController;
import fi.otavanopisto.muikku.schooldata.WorkspaceEntityController;
import fi.otavanopisto.muikku.schooldata.entity.User;
import fi.otavanopisto.muikku.schooldata.entity.UserAddress;
import fi.otavanopisto.muikku.schooldata.entity.UserPhoneNumber;
import fi.otavanopisto.muikku.schooldata.entity.UserProperty;
import fi.otavanopisto.muikku.users.UserController;
import fi.otavanopisto.muikku.users.UserEmailEntityController;
import fi.otavanopisto.muikku.users.UserSchoolDataIdentifierController;

@RequestScoped
@Named
@Stateful
public class SessionBackingBean {

  @Inject
  private SessionController sessionController;

  @Inject
  private LocaleController localeController;

  @Inject
  private UserController userController;

  @Inject
  private WorkspaceEntityController workspaceEntityController;

  @Inject
  private SystemSettingsController systemSettingsController;

  @Inject
  private WorkspaceBackingBean workspaceBackingBean;

  @Inject
  private ForumController forumController;

  @Inject
  private UserEmailEntityController userEmailEntityController;

  @Inject
  private UserSchoolDataController userSchoolDataController;
  
  @Inject
  private UserSchoolDataIdentifierController userSchoolDataIdentifierController;

  @PostConstruct
  public void init() {
    loggedUserRoleArchetype = null;
    loggedUserName = null;
    testsRunning = StringUtils.equals("true", System.getProperty("tests.running"));
    bugsnagApiKey = systemSettingsController.getSetting("bugsnagApiKey");
    bugsnagEnabled = StringUtils.isNotBlank(bugsnagApiKey);
    loggedUserId = null;
    loggedUser = null;
    canAccessEnvironmentForum = forumController.isEnvironmentForumActive() && hasEnvironmentPermission(ForumResourcePermissionCollection.FORUM_ACCESSENVIRONMENTFORUM);

    if (sessionController.isLoggedIn()) {
      UserEntity loggedUser = sessionController.getLoggedUserEntity();
      if (loggedUser != null) {
        String activeSchoolDataSource = sessionController.getLoggedUserSchoolDataSource();
        String activeUserIdentifier = sessionController.getLoggedUserIdentifier();
        
        EnvironmentRoleEntity roleEntity = userSchoolDataIdentifierController.findUserSchoolDataIdentifierRole(sessionController.getLoggedUser());
        if (roleEntity != null) {
          loggedUserRoleArchetype = roleEntity.getArchetype();
        }

        User user = userController.findUserByDataSourceAndIdentifier(activeSchoolDataSource, activeUserIdentifier);
        if (user != null) {
          if (!loggedUserRoleArchetype.equals(EnvironmentRoleArchetype.STUDENT)) {
            loggedUserName = String.format("%s %s (%s)", user.getFirstName(), user.getLastName(),
                resolveLoggedUserRoleText());
          }
          else if (user.getNickName() != null) {
            loggedUserName = String.format("%s %s (%s)", user.getNickName(), user.getLastName(),
                user.getStudyProgrammeName());
          }
          else {
            loggedUserName = user.getDisplayName();
          }
        }
      }

      this.loggedUserId = sessionController.getLoggedUserEntity().getId();
      this.loggedUser = sessionController.getLoggedUser().toId();

      if (!sessionController.hasEnvironmentPermission(ForumResourcePermissionCollection.FORUM_ACCESSENVIRONMENTFORUM)
          || !sessionController.isActiveUser()) {
        this.areaPermissions = null;
      }
      else {
        List<EnvironmentForumArea> forumAreas = forumController.listEnvironmentForums();
        Map<Long, AreaPermission> areaPermissions = new HashMap<>();

        for (EnvironmentForumArea forumArea : forumAreas) {
          AreaPermission areaPermission = new AreaPermission(
              sessionController.hasPermission(ForumResourcePermissionCollection.FORUM_EDIT_ENVIRONMENT_MESSAGES,
                  forumArea),
              sessionController.hasPermission(ForumResourcePermissionCollection.FORUM_DELETE_ENVIRONMENT_MESSAGES,
                  forumArea));
          areaPermissions.put(forumArea.getId(), areaPermission);
        }

        try {
          this.areaPermissions = new ObjectMapper().writeValueAsString(areaPermissions);
        }
        catch (JsonProcessingException e) {
          this.areaPermissions = null;
        }
      }
    }
    else {
      this.areaPermissions = null;
    }

    if (sessionController.isLoggedIn()) {
      UserEntity userEntity = sessionController.getLoggedUserEntity();
      User user = userController.findUserByDataSourceAndIdentifier(sessionController.getLoggedUserSchoolDataSource(), sessionController.getLoggedUserIdentifier());
      List<UserAddress> userAddresses = userController.listUserAddresses(user);
      List<UserPhoneNumber> userPhoneNumbers = userController.listUserPhoneNumbers(user);
        
      displayName = user.getNickName() == null ? user.getDisplayName() : String.format("%s %s (%s)", user.getNickName(), user.getLastName(), user.getStudyProgrammeName());
        
      studyStartDate = user.getStudyStartDate();
      studyEndDate = user.getStudyEndDate();
      studyTimeEnd = user.getStudyTimeEnd();
      studyTimeLeftStr = "";

      if (studyTimeEnd != null) {
        OffsetDateTime now = OffsetDateTime.now();
        Locale locale = sessionController.getLocale();
          
        if (now.isBefore(studyTimeEnd)) {
          long studyTimeLeftYears = now.until(studyTimeEnd, ChronoUnit.YEARS);
          now = now.plusYears(studyTimeLeftYears);
          if (studyTimeLeftYears > 0) {
            studyTimeLeftStr += studyTimeLeftYears + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.y");
          }
            
          long studyTimeLeftMonths = now.until(studyTimeEnd, ChronoUnit.MONTHS);
          now = now.plusMonths(studyTimeLeftMonths);
          if (studyTimeLeftMonths > 0) {
            if (studyTimeLeftStr.length() > 0)
              studyTimeLeftStr += " ";
            studyTimeLeftStr += studyTimeLeftMonths + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.m");
          }
          
          long studyTimeLeftDays = now.until(studyTimeEnd, ChronoUnit.DAYS);
          now = now.plusDays(studyTimeLeftDays);
          if (studyTimeLeftDays > 0) {
            if (studyTimeLeftStr.length() > 0)
              studyTimeLeftStr += " ";
            studyTimeLeftStr += studyTimeLeftDays + " " + localeController.getText(locale, "plugin.profile.studyTimeEndShort.d");
          }
        }

        long studyTimeLeftMonths = now.until(studyTimeEnd, ChronoUnit.MONTHS);
        now = now.plusMonths(studyTimeLeftMonths);
        if (studyTimeLeftMonths > 0) {
          if (studyTimeLeftStr.length() > 0)
            studyTimeLeftStr += " ";
          studyTimeLeftStr += studyTimeLeftMonths + " "
              + localeController.getText(locale, "plugin.profile.studyTimeEndShort.m");
        }

        long studyTimeLeftDays = now.until(studyTimeEnd, ChronoUnit.DAYS);
        now = now.plusDays(studyTimeLeftDays);
        if (studyTimeLeftDays > 0) {
          if (studyTimeLeftStr.length() > 0)
            studyTimeLeftStr += " ";
          studyTimeLeftStr += studyTimeLeftDays + " "
            + localeController.getText(locale, "plugin.profile.studyTimeEndShort.d");
        }
      }

      ArrayList<String> foundAddresses = new ArrayList<>();
      for (UserAddress userAddress : userAddresses) {
        foundAddresses.add(String.format("%s %s %s %s", userAddress.getStreet(), userAddress.getPostalCode(),
            userAddress.getCity(), userAddress.getCountry()));
      }
      try {
        this.addresses = new ObjectMapper().writeValueAsString(foundAddresses);
      } catch (JsonProcessingException e) {
        this.addresses = null;
      }

      ArrayList<String> foundPhoneNumbers = new ArrayList<>();
      for (UserPhoneNumber userPhoneNumber : userPhoneNumbers) {
        foundPhoneNumbers.add(userPhoneNumber.getNumber());
      }

      try {
        this.phoneNumbers = new ObjectMapper().writeValueAsString(foundPhoneNumbers);
      } catch (JsonProcessingException e) {
        this.phoneNumbers = null;
      }

      SchoolDataIdentifier identifier = userEntity.defaultSchoolDataIdentifier();
      List<String> foundEmails = userEmailEntityController.getUserEmailAddresses(identifier);
      try {
        this.emails = new ObjectMapper().writeValueAsString(foundEmails);
      } catch (JsonProcessingException e) {
        this.emails = null;
      }
    }
  }

  public boolean getLoggedIn() {
    return sessionController.isLoggedIn();
  }

  public boolean getIsStudent() {

muikku/src/main/webapp/WEB-INF/templates/deprecated/flex-base.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html" 
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:jsf="http://xmlns.jcp.org/jsf"
  xmlns:ui="http://java.sun.com/jsf/facelets">

  <f:view locale="#{sessionBackingBean.locale}">
  
    <head>
      <ui:insert name="title">
      <title>#{i18n.text['plugin.site.title']}</title>
      </ui:insert>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta http-equiv="x-ua-compatible" content="ie=edge" />
      <meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport" />
      <ui:insert name="meta"></ui:insert>
      <script type="text/javascript">
          var CONTEXTPATH = "#{request.contextPath}";
          var MUIKKU_LOGGED_USER_ID = parseInt('#{sessionBackingBean.loggedUserId}')||null;
          var MUIKKU_LOGGED_USER = '#{sessionBackingBean.loggedUser}'||null;
          var MUIKKU_LOGGEDIN = #{sessionBackingBean.loggedIn};
          var CREATE_PERMANENT_CHATROOM=#{sessionBackingBean.hasEnvironmentPermission('CREATE_PERMANENT_CHATROOM')};
      </script>
      
      <ui:fragment rendered="#{sessionBackingBean.bugsnagEnabled}">
        <script defer="defer" type="text/javascript" src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js" data-apikey="#{sessionBackingBean.bugsnagApiKey}"></script>
      </ui:fragment>
      
      <!-- jQuery -->
      <script type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery/2.1.3/jquery.min.js"/>
      
      <!-- jQuery UI -->
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jqueryui/1.11.2/jquery-ui.min.js"/>

      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jqueryui/1.11.2/i18n/datepicker-fi.js"/>
      
      <script defer="defer" type="text/javascript">
        $(document).ready(function () {
          $.datepicker.setDefaults($.datepicker.regional['#{sessionBackingBean.locale}']);
        });
      </script>
      
      <!--  jQuery Touch Punch or jQuery Mobile? -->
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"/>
      
      <ui:fragment rendered="#{sessionBackingBean.testsRunning}"> 
        <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate/1.0.1/jquery.simulate.js"></script>
        <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate-ext/1.3.0/jquery.simulate.ext.js"></script>
        <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery-simulate-ext/1.3.0/jquery.simulate.drag-n-drop.js"></script>
      </ui:fragment>
      
      <script defer="defer" type="text/javascript" jsf:name="/scripts/debug.js" jsf:rendered="#{sessionBackingBean.testsRunning}"/>
      
      <!-- Moment -->
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/moment/2.10.6/moment-with-locales.min.js"/>    
      
      <!-- Notification Queue -->
      <script defer="defer" type="text/javascript" jsf:name="/scripts/notificationqueue/notificationqueue.js"/>
      
      <!-- Api resources -->
      <script defer="defer" type="text/javascript" src="#{request.contextPath}/rest/meta/resources?format=js"></script>
      
      <!-- Async -->
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/async/0.9.0/async.js"/>
      
      <!-- ObjectPath, jQuery REST -->
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/interpreter.js"></script>
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/parse.js"></script>
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/objectpathjs/0.0.1/tokens.js"></script>
      <script defer="defer" type="text/javascript" src="//cdn.muikkuverkko.fi/libs/jquery.rest/1.0.2/jquery.rest.min.js"></script>
      
      <!-- Api -->
      <script defer="defer" type="text/javascript" jsf:name="/scripts/api/api.js"/>

      <!-- Websocket -->
      <script defer="defer" type="text/javascript" jsf:name="/scripts/widgets/controllers/websocket.js" />

      <!-- Heartbeat -->
      <script defer="defer" type="text/javascript" jsf:name="/scripts/gui/heartbeat.js"/>
      
      <!-- Language -->
      <script defer="defer" type="text/javascript" jsf:name="/scripts/gui/language.js"/>
      
      <ui:insert name="scripts-main"></ui:insert>
      <ui:insert name="scripts"></ui:insert>

      <!-- Flex Grid -->
      <link rel="stylesheet" type="text/css" href="//cdn.muikkuverkko.fi/libs/fni-flexgrid/1.0.0/flexgrid.css"/>
      <link rel="stylesheet" type="text/css" href="//cdn.muikkuverkko.fi/assets/muikku-icons/1.2.5/style.css"/>
      <ui:insert name="styles-main"></ui:insert>
      <ui:insert name="styles"></ui:insert>
    </head>
  
    <body>
      <ui:insert name="body"></ui:insert>
      
      <!-- Google Analytics -->
      <ui:fragment rendered="#{environmentBackingBean.hasGoogleAnalyticsTrackingId}">
        <script>
          window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
          ga('create', '#{environmentBackingBean.googleAnalyticsTrackingId}', 'auto');
          if(MUIKKU_LOGGEDIN){
            ga('set', 'cd1', 'loggedIn');
          }
          else{
            ga('set', 'cd1', 'anonymous');
          }
          ga('send', 'pageview');
        </script>
        <script async="async" src='https://www.google-analytics.com/analytics.js'></script>
      </ui:fragment>
      <!-- End Google Analytics -->

    <ui:insert name="scripts-end"></ui:insert>
    </body>

  </f:view>
</html>

muikku/src/main/webapp/WEB-INF/templates/deprecated/flex-config-view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
xmlns="http://www.w3.org/1999/xhtml" 
xmlns:m="http://www.ofw.fi/xml/2013/muikku/components-taglib.xsd"
xmlns:ui="http://java.sun.com/jsf/facelets" 
xmlns:f="http://java.sun.com/jsf/core"
xmlns:c="http://java.sun.com/jsp/jstl/core"
xmlns:h="http://java.sun.com/jsf/html"
template="flex-main-env.xhtml">

  <ui:define name="styles">
    <link rel="stylesheet" type="text/css" href="/css/deprecated/flex/flex-main.css"/>
    <link rel="stylesheet" type="text/css" href="/css/deprecated/flex/flex-main-functionality.css"/>
    <link rel="stylesheet" type="text/css" href="/css/deprecated/flex/flex-reading-view.css"/>
    <ui:insert name="main-functionality-styles"></ui:insert>    
  </ui:define>  

  <ui:define name="grid-content"> 
    <div id="configView" class="mf-content-master">
      <ui:insert name="mf-content-master"> 
        <ui:insert name="mf-content-area">
          <div class="mf-content-area flex-row">
            <div class="lg-flex-cell-full md-flex-cell-full sm-flex-cell-full">
            <ui:insert name="mf-content-area-instance">
            
            </ui:insert>
            </div>
          </div>
        </ui:insert>
      </ui:insert>
    </div>
  </ui:define>
    
</ui:composition>

muikku/src/main/webapp/WEB-INF/templates/deprecated/flex-materials-fullscreen-view.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition
xmlns="http://www.w3.org/1999/xhtml" 
xmlns:m="http://www.ofw.fi/xml/2013/muikku/components-taglib.xsd"
xmlns:ui="http://java.sun.com/jsf/facelets" 
xmlns:f="http://java.sun.com/jsf/core"
xmlns:c="http://java.sun.com/jsp/jstl/core"
xmlns:h="http://java.sun.com/jsf/html"
template="flex-main.xhtml">

  <ui:define name="title">
    <title>#{workspaceBackingBean.workspaceName} - #{i18n.text['plugin.site.title']}</title>
  </ui:define>

  <ui:define name="main-content">
    <div class="flex-grid">
    
    <ui:insert name="grid-content"></ui:insert>
    </div>
  </ui:define>
  
  <ui:define name="footer">
  
  </ui:define>
    
</ui:composition>